export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS"
export const BOOK_ADDED_TO_CART = "BOOK_ADDED_TO_CART"
export const BOOK_INCREMENT_OR_DECREMENT = "BOOK_INCREMENT_OR_DECREMENT";